name: Resources health-check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 * *' # At 12:00 AM, on day 15 of the month

jobs:
  Health-check:
    runs-on: ubuntu-latest
    timeout-minutes: 90 # higher timeout because network requests can be slow in CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Path resources healthcheck
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_baseUrl: https://www.sherpa.guide
          CYPRESS_retries: 0
          CYPRESS_pageLoadTimeout: 60000
          CYPRESS_requestTimeout: 30000
          CYPRESS_ZENSCRAPE_API_KEY: ${{ secrets.ZENSCRAPE_API_KEY }}
          CYPRESS_YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        with:
          build: npm run build:packages # cypress.config.ts depends on read utils from @sherpa/data package
          project: apps/web
          browser: chrome
          spec: |
            **/cypress/e2e/paths/health-check.cy.ts
