name: Resources health-check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */10 * *' # runs tests at 12:00 AM, every 10 days

jobs:
  Health-check:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # to prevent a hanging process from using all CI minutes
    steps:
      - uses: actions/checkout@v2
      - name: Path resources healthcheck
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_baseUrl: https://the-learning-path.vercel.app
          CYPRESS_retries: 2
          CYPRESS_pageLoadTimeout: 60000
          CYPRESS_requestTimeout: 60000
        with:
          spec: cypress/integration/paths/resources.spec.ts # Running only resources tests
