name: 'Production'
on:
  push:
    branches:
      - 'main'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # to prevent a hanging process from using all CI minutes
    steps:
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: amondnet/vercel-action@v25
        id: vercel-deployment
        with:
          vercel-project-name: 'the-learning-path'
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_ACCOUNT_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_USER_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          github-comment: true
          github-deployment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
