name: 'Production'
on:
  push:
    branches:
      - 'main'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        id: vercel-deployment
        with:
          vercel-project-name: 'the-learning-path'
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_ACCOUNT_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_USER_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          github-comment: true
          github-deployment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
